### PR TITLE
Add forck file

### PR DESCRIPTION
**Pull request by Liu-Xiaoqiang**
I added one new file which is needed to add in this branch.

### CODE REVIEW

**Comment by leavs** [comment]
Can you describe it again?

**Comment by Liu-Xiaoqiang** [comment]
OK.
1. I want.
2. I can.



Kind regards,
Nicky
CHIPSEE CO., LIMITED
Address:Xinyuan Science Park B406, 97 Changping Road, Changping District, Beijing, 102206, China
TEL:+8610-62105170
Website:www.chipsee.com
 ***@***.***
Skype: ***@***.***

 
From: leavs
Date: 2022-01-04 14:47
To: leavs/GitStudy
CC: Xiao Qiang; Author
Subject: Re: [leavs/GitStudy] Add forck file (PR #1)
Can you describe it again?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leavs** [comment]
great.
I will confirm it.



***@***.***
 
From: Xiao Qiang
Date: 2022-01-04 14:48
To: leavs/GitStudy
CC: leavs; Comment
Subject: Re: [leavs/GitStudy] Add forck file (PR #1)
OK. 
1. I want. 
2. I can. 



Kind regards, 
Nicky 
CHIPSEE CO., LIMITED 
Address:Xinyuan Science Park B406, 97 Changping Road, Changping District, Beijing, 102206, China 
TEL:+8610-62105170 
Website:www.chipsee.com 
***@***.*** 
Skype: ***@***.*** 


From: leavs 
Date: 2022-01-04 14:47 
To: leavs/GitStudy 
CC: Xiao Qiang; Author 
Subject: Re: [leavs/GitStudy] Add forck file (PR #1) 
Can you describe it again? 
— 
Reply to this email directly, view it on GitHub, or unsubscribe. 
Triage notifications on the go with GitHub Mobile for iOS or Android. 
You are receiving this because you authored the thread.Message ID: ***@***.***> 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Liu-Xiaoqiang** [comment]
Thanks.

**Pull request merged**
